# Generated by Django 4.2.5 on 2023-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='expirado',
            field=models.BooleanField(default=False),
        ),
    ]
