# Generated by Django 4.2.5 on 2023-10-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
