# Generated by Django 4.2.5 on 2024-01-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
