# Generated by Django 4.2.5 on 2023-10-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodetalle',
            name='imagen2D',
            field=models.ImageField(blank=True, null=True, upload_to='productos/imagenes2d/'),
        ),
    ]
