# Generated by Django 4.2.5 on 2023-10-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_productodetalle_imagen2d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodetalle',
            name='cantidad',
        ),
    ]
