# Generated by Django 4.2.5 on 2023-10-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_productodetalle_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodetalle',
            name='estado',
        ),
    ]
