# Generated by Django 4.2.5 on 2023-10-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_productodetalle_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodetalle',
            name='tamaño',
        ),
        migrations.DeleteModel(
            name='Tamaño',
        ),
    ]
