# Generated by Django 4.2.5 on 2023-10-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_productodetalle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodetalle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.color'),
        ),
    ]
