# Generated by Django 4.2.5 on 2023-12-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
