# Generated by Django 4.2.5 on 2023-10-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
