# Generated by Django 4.2.5 on 2023-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_productodetalle_imagen2d'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='productos_detalle',
            field=models.ManyToManyField(blank=True, through='transacciones.CarritoProductoDetalle', to='productos.productodetalle'),
        ),
    ]
